---

- name: Delete certificate folder if renewing certificates
  file:
    path: /etc/elasticsearch/certs
    state: absent
  when: elastic_certificates_renew | bool

- name: Create certificate folder
  file:
    path: /etc/elasticsearch/certs
    state: directory
    owner: root
    group: "{{ elastic_group }}"
    mode: 0o750

- name: Upload certificate generation configuration file
  copy:
    content:
      "{{ elastic_certificates_config | to_nice_yaml(indent=2) }}"
    dest: /etc/elasticsearch/certs/elasticsearch-certutil.yml
    mode: 0o640
    owner: root
    group: "{{ elastic_group }}"

- name: Create a CA
  command: >-
    {{
      elastic_certificate_ca_command
      | default(_elastic_certificate_ca_command, true)
    }}
  args:
    creates: /etc/elasticsearch/certs/elastic-stack-ca.zip

- name: Extract CA zip
  unarchive:
    src: /etc/elasticsearch/certs/elastic-stack-ca.zip
    dest: /etc/elasticsearch/certs/
    remote_src: true
    mode: 0o0640
    owner: root
    group: "{{ elastic_group }}"

- name: Generate the certificates
  command: >-
    {{
      elastic_certificate_cert_command
      | default(_elastic_certificate_cert_command, true)
    }}
  args:
    creates: /etc/elasticsearch/certs/elasticsearch-certs.zip
