---

- name: Remove existing keystore passwords
  command:
    /usr/share/elasticsearch/bin/elasticsearch-keystore remove "{{ item }}"
  register: result
  failed_when:
    - result is failed
    - result.stderr is not search('does not exist in the keystore')
  when: elastic_certificates_password_renew | bool
  loop:
    - xpack.security.transport.ssl.secure_key_passphrase
    - xpack.security.http.ssl.secure_key_passphrase

- name: List keystore settings
  command: /usr/share/elasticsearch/bin/elasticsearch-keystore list
  register: _elastic_keystore_settings
  changed_when: false

- name: Add certificates password to elastic keystore
  shell: |
    set -o pipefail;
    echo '{{ elastic_certificates_password }}' |
      /usr/share/elasticsearch/bin/elasticsearch-keystore add \
        '{{ item }}'
  args:
    executable: /bin/bash
  when: >-
    _elastic_keystore_settings.stdout is not search(item)
  loop:
    - xpack.security.transport.ssl.secure_key_passphrase
    - xpack.security.http.ssl.secure_key_passphrase
  notify: elastic restart service
