---

- name: Remove existing keystore passwords
  command:
    /usr/share/elasticsearch/bin/elasticsearch-keystore remove "{{ item }}"
  register: result
  failed_when:
    - result is failed
    - result.stderr is search('does not exist in the keystore')
  when: elastic_certificate_password_renew | bool
  loop:
    - xpack.security.transport.ssl.keystore.secure_password
    - xpack.security.transport.ssl.truststore.secure_password
    - xpack.security.http.ssl.keystore.secure_password
    - xpack.security.http.ssl.truststore.secure_password

- name: List keystore settings
  command: /usr/share/elasticsearch/bin/elasticsearch-keystore list
  register: _elastic_keystore_settings
  changed_when: false

- name: Add certificate password to elastic keystore
  shell: |
    set -o pipefail;
    echo {{ elastic_certificates_password }} |
      /usr/share/elasticsearch/bin/elasticsearch-keystore add \
        {{ item }}
  args:
    executable: /bin/bash
  when: >-
    _elastic_keystore_settings.stdout is not search(item)
  loop:
    - xpack.security.transport.ssl.keystore.secure_password
    - xpack.security.transport.ssl.truststore.secure_password
    - xpack.security.http.ssl.keystore.secure_password
    - xpack.security.http.ssl.truststore.secure_password
  notify: elastic restart service
