---

- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Add Elasticsearch Signing Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{
              elastic_major_version }}.x/apt stable main"

- name: Install Elasticsearch and dependencies
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - "elasticsearch={{ elastic_major_version }}.{{
              '.*' if elastic_minor_version == '*' else elastic_minor_version | string + '.*'}}"
      - unzip
  notify: elastic restart service

- name: Disable automatic updates
  copy:
    content: |
      Unattended-Upgrade::Package-Blacklist {
        "elasticsearch";
      };
    dest: /etc/apt/apt.conf.d/55elasticsearch-disable
  when: elastic_disable_auto_update | bool
