---

- name: Check OS is supported
  assert:
    that:
      - "ansible_os_family in ['Debian', 'RedHat']"
    msg: "{{ ansible_os_family }} is not supported"

- name: Check if an `elastic` user pass is available
  assert:
    that:
      - "elastic_builtin_users_password_backup_file != None
         or elastic_users
            | selectattr('name', 'equalto', 'elastic')
            | list
            | length > 0
        "
    msg: >-
      either `elastic_builtin_users_password_backup_file` must be set
      or `elastic_users` must contain a custom password for the `elastic` user
  when: elastic_combined_config.xpack.security.enabled | d(false) | bool

- name: Check GCP credentials
  assert:
    that:
      - "not elastic_plugin_gcs_enabled | bool
         or elastic_plugin_gcs_enabled | bool
         and elastic_plugin_gcs_credentials is mapping"
    msg: "GCP credentials must be set if the repository-gcs plugin is enabled"
