---

- include_tasks: variables.yml

- include_tasks: assertions.yml

- include_tasks: core/system.yml

- include_tasks: "core/install/{{ ansible_os_family }}.yml"

- include_tasks: core/keystore.yml

- include_tasks: certificates/upload.yml
  when: elastic_certificates != None

- include_tasks: certificates/keystore.yml
  when:
    - elastic_certificates_password != None
    - elastic_certificates != None

- include_tasks: core/configure.yml

- meta: flush_handlers

- include_tasks: core/builtin-users.yml
  when: elastic_builtin_users_set_random_passwords | bool

- include_tasks: indexes.yml

- include_tasks: realms/native.yml
