---

- name: Read ingest pipelines
  set_fact:
    _elastic_pipelines: "{{ (_elastic_pipelines | d([]))
                            + ((lookup('file', item.src) | from_yaml).pipelines
                                if 'src' in item else [item])
                          }}"
  loop: "{{ elastic_ingest_pipelines }}"

- name: Import ingest pipelines
  uri:
    url: "{{ elastic_node_address }}/_ingest/pipeline/{{ item.description | replace('-', '_') }}"
    method: PUT
    body: "{{ item }}"
    body_format: json
    headers:
      Content-Type: application/json
    force_basic_auth: true
    url_username: "{{ _elastic_elastic_user['name'] }}"
    url_password: "{{ _elastic_elastic_user['pass'] }}"
    validate_certs: false
    return_content: true
  loop: "{{ _elastic_pipelines | d([]) }}"
