---

- name: Restart elasticsearch service
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: true
  listen: elastic restart service

- name: Check that elastic search has started successfully
  uri:
    url: >-
      http{{ elastic_certificate_file | ternary('s', '') }}://{{
        elastic_bind_host }}:{{
        elastic_bind_port }}
    return_content: true
    validate_certs: false
  register: result
  until: result is success
  retries: 11
  delay: 5
  failed_when:
    - result is failed
    - result.content is not search('missing authentication credentials')
  listen: elastic restart service
