---

- name: Check if a keystore exists
  stat:
    path: /etc/elasticsearch/elasticsearch.keystore
  register: result

- name: Create elasticsearch keystore
  command: /usr/share/elasticsearch/bin/elasticsearch-keystore create
  when: not result.stat.exists | bool
