---

- name: Start the elasticsearch service
  systemd:
    name: elasticsearch
    state: started
    enabled: true

- name: Check that elastic search has started successfully
  uri:
    url: "{{ elastic_node_address }}"
    return_content: true
    validate_certs: false
  register: result
  until: result is success
  retries: 11
  delay: 5
  failed_when:
    - result is failed
    - result.content is not search('missing authentication credentials')
