---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint --config-file molecule/default/yamllint.yml .
  ansible-lint .
  flake8
platforms:
  - name: "${MOLECULE_INSTANCE_NAME:-systemd-ubuntu-18.04}"
    image: "${MOLECULE_DISTRO:-jrei/systemd-ubuntu:18.04}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - '9200:9200/tcp'
    command: /lib/systemd/systemd
    privileged: true
provisioner:
  name: ansible
  options:
    vvv: true
  env:
    IN_MOLECULE: 'true'
scenario:
  name: default
verifier:
  name: testinfra
  enabled: false
  lint:
    name: flake8
