---

- name: Prepare
  hosts: all
  roles:
    - reallyenglish.apt-repo
    - geerlingguy.java
    - geerlingguy.git
    - nkakouros.easyrsa
  vars:
    apt_repo_to_add:
      - ppa:webupd8team/java

    java_packages:
      - openjdk-8-jre

    easyrsa_servers:
      - name: elastic
        pass: 'nk}$Q%];a3Gy$E!QvT8E'

    easyrsa_clients:
      - name: logstash
        pass: 'nk}$Q%];a3Gy$E!QvT8E'
      - name: kibana-backend
        pass: 'nk}$Q%];a3Gy$E!QvT8E'
      - name: beats
        pass: 'nk}$Q%];a3Gy$E!QvT8E'

    easyrsa_to_pkcs12: "{{ easyrsa_clients + easyrsa_servers }}"
    easyrsa_to_pkcs8: "{{ easyrsa_clients + easyrsa_servers }}"
    easyrsa_to_pkcs1: "{{ easyrsa_clients + easyrsa_servers }}"

    easyrsa_download: []
    easyrsa_download_pki: true
    easyrsa_download_dir: '~/'
  pre_tasks:
    - name: Install packages required by ansible modules
      package:
        name: "{{ package }}"
      loop: "{{ packages }}"
      loop_control:
        loop_var: package
      vars:
        packages:
          - gnupg
          - software-properties-common
