---

- name: Prepare
  hosts: all
  roles:
    - reallyenglish.apt-repo
    - geerlingguy.java
    - nkakouros.elasticsearch
  vars:
    apt_repo_to_add:
      - ppa:webupd8team/java
    java_packages:
      - openjdk-8-jre
