---

- name: Create variable with built-in users
  set_fact:
    _elastic_builtin_users:
      - apm_system
      - kibana
      - logstash_system
      - beats_system
      - remote_monitoring_user
      - elastic

- name: Create users
  uri:
    url: "{{ elastic_node_address }}/_security/user/{{ _elasticsearch__user.name }}"
    method: POST
    body:
      enabled: "{{ _elasticsearch__user.enabled | default(true) }}"
      email: "{{ _elasticsearch__user.email | default(omit) }}"
      full_name: "{{ _elasticsearch__user.full_name | default(omit) }}"
      password: "{{ _elasticsearch__user.pass }}"
      roles: "{{ _elasticsearch__user.roles
                 | default(_elasticsearch__user.groups
                 | default(omit))
              }}"
    body_format: json
    headers:
      Content-Type: application/json
    force_basic_auth: true
    url_username: "{{ _elastic_elastic_user['name'] }}"
    url_password: "{{ _elastic_elastic_user['pass'] }}"
    validate_certs: false
    return_content: true
  register: _result
  failed_when:
    - _result is failed
    - _result.json.error.reason is not contains("is reserved and only the password can be changed;")
  when: _elasticsearch__user.name not in _elastic_builtin_users
  loop: "{{ elastic_users }}"
  loop_control:
    loop_var: _elasticsearch__user

- name: Change user password
  uri:
    url: "{{ elastic_node_address }}/_security/user/{{ _elasticsearch__user.name }}/_password"
    method: POST
    body:
      password: "{{ _elasticsearch__user.pass }}"
    body_format: json
    headers:
      Content-Type: application/json
    force_basic_auth: true
    url_username: "{{ _elastic_elastic_user['name'] }}"
    url_password: "{{ _elastic_elastic_user['pass'] }}"
    validate_certs: false
    return_content: true
  loop: "{{
      elastic_users
      | rejectattr('name', 'equalto', 'elastic')
      | list
      +
      elastic_users
      | selectattr('name', 'equalto', 'elastic')
      | list
    }}"
  loop_control:
    loop_var: _elasticsearch__user

- name: Keep track of `elastic` user's new password
  set_fact:
    _elastic_elastic_user: >-
      {{
        elastic_users
        | selectattr('name', 'equalto', 'elastic')
        | list
        | first
      }}
