---

name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          # - image: jrei/systemd-ubuntu:16.04
          #  instance: systemd-ubuntu-16.04
          - image: jrei/systemd-ubuntu:18.04
            instance: systemd-ubuntu-18.04
            # - image: jrei/systemd-ubuntu:20.04
            #  instance: systemd-ubuntu-20.04
            # - image: jrei/systemd-centos:7
            #   instance: systemd-centos-7
            # - image: jrei/systemd-centos:8
            #   instance: systemd-centos-8
            # - image: jrei/systemd-debian:9
            #   instance: systemd-debian-9
            # - image: jrei/systemd-debian:10
            #   instance: systemd-debian-10
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1

      - name: Install molecule
        run: pip3 install molecule ansible ansible-lint docker

      - name: Run molecule
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro.image }}
          MOLECULE_INSTANCE_NAME: ${{ matrix.distro.instance }}
